name: Build Docker Image
on:
  push:
    branches:
      - main
jobs:
    build:
      name: push docker image to docker hub1
      runs-on: linux-run01
      ##runs-on: karthik-win
      steps:
        - uses: actions/checkout@v2
        - name: login to docker hub
          id: docker-hub
          env:
            username: ${{secrets.DOCKERHUB_USERNAME}}
            password: ${{secrets.DOCKERHUB_PASSWORD}}
            DOCKER_TOKEN: ${{ env.DOCKERHUB_TOKEN }}
          run: |
            docker login -u $username -p $password
            ##docker login -u karthiksekaran86 -p Treasure#09
        - name: build the docker image
          id: build-docker-image
          run: |
            ls -la 
            docker build . -f Dockerfile -t pradeepln08/SpringDemoApp:latest
        - name: push the docker image
          id: push-docker-image
          run: docker push ${{secrets.DOCKERHUB_USERNAME}}/ocp-test-1:latest
