name: Java CI with Maven

on:
  push:
    branches: ["main"]
  
jobs:
  build:
    runs-on: winrun01

    steps:
      - name: PWD
        run: pwd
        
      - name: Go to path
        run: path target
    
      - name: PWD
        run: pwd
    
