name: Java CI with Maven

on:
  #watch:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: winrun01

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"
          cache: maven
          #env: gittoken = ${{ env.GITHUBTOKEN }}

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Working Directory
        run: pwd

      - name: commit and push to gitHub
        run: |
          cd target             
          pwd
          copy SpringDemoApp.jar C:\Users\91984\Documents\GitHub\SpringDemoApp\target 
          git add SpringDemoApp.jar
          git remote add origin github@github.com/pradeepln08/SpringDemoApp.git
          git commit -m 'files changed'            
          git push

        #Start-Process java -Argumentlist '-jar' , 'SpringDemoApp.jar' -wait -RedirectStandardOutput '.\console.out' -RedirectStandardError '.\console.err'
