name: Java CI with Maven

on:
  push:
    branches: ["main"]
  
jobs:
  build:
    runs-on: winrun01

    steps:
      - name: PWD
        run: pwd

      - name: Go to the folder
        run: chdir target

      - name: Go to the folder
        run: cd target  
        
      - name: Go to the folder
        run: chdir /SpringDemoApp/target/  
      - name: PWD
        run: pwd
    
      
