name: Java CI with Maven

on:
  watch:
  #push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: winrun01

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml
        
      - name: Working Directory
        run: pwd
        
      - name: Go to target folder
        run: |
            cd target 
            pwd
            copy SpringDemoApp.jar C:\Users\91984\Documents\GitHub\SpringDemoApp\target            
       #Start-Process java -Argumentlist '-jar' , 'SpringDemoApp.jar' -wait -RedirectStandardOutput '.\console.out' -RedirectStandardError '.\console.err'                                     
