name: Java CI with Maven

on:
  push:
    branches: ["main"]
  
jobs:
  build:
    runs-on: winrun01

    steps:
      - name: PWD
        run: pwd
        
      - name: Go to path
        run: cd/
      
      - name: Go to path1
        run: cd C:\Users\91984\Documents\GitHub\SpringDemoApp\actions-runner\_work\SpringDemoApp\SpringDemoApp\target
    
      - name: PWD
        run: pwd
    
