# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package and Commit

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: winrun01
    permissions:
      contents: write
      packages: write
      deployments: write
      statuses: write
      actions: write
      checks: read
      
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven 
      run: mvn -B package --file pom.xml

    - name: Move to target directory
      run: |
            cd target
            git config --global user.name "pradeepln08" 
            git config --global user.email "pradeepln08@gmail.com" 
            git add . 
            git status 
            git commit -am "yml commit success"
            echo https://${{secrets.GITHUBTOKEN}}@github.com/pradeepln08/springdemoapp.git 
            git remote set-url origin https://${{secrets.GITHUBTOKEN}}@github.com/pradeepln08/springdemoapp.git 
            git push
      
