name: Java CI with Maven

on:
  push:
    branches: ["main"]
  
jobs:
  build:
    runs-on: winrun01

    steps:
      - name: PWD
        run: pwd

      - name: Go to the folder
        run: cd

      - name: Go to the folder
        run: cd target
    
      - name: PWD
        run: pwd
    
